### ISSUE TITLE
Multi view camera rendering settings

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#707]
How to set such a scene:
https://wuminye.github.io/NHR/datasets.html
![image](https://user-images.githubusercontent.com/34391447/196369827-fa57794e-2342-4c84-a543-32be5059dbf8.png)

**Comment by LogWell** [comment]
The primitives can be corresponding images, or cameras like: https://www-users.cse.umn.edu/~hspark/CSci5980/csci5980_3dvision.html
![image](https://user-images.githubusercontent.com/34391447/196373119-685622ef-7b2a-4279-bb6a-245a404946cb.png)

**Comment by marcomusy** [comment]
if you have the individual images and orientations in space you can create 
```python
pict1 = Picture("pic1.jpg")
pict1.orientation(pic1_vector)
pict1.pos(pic1_position)
...
```

**Comment by LogWell** [comment]
In addition, can I define a structure that contains an image and a wireframe model of the camera, and then treat this as a whole and place it somewhere and set the orientation?

![image](https://user-images.githubusercontent.com/34391447/197108320-910cd66a-f9ad-4037-8eea-b3d7b39f60be.png)

**Comment by marcomusy** [comment]
You can use an `Assembly` object to treat multiple objects as a single one:
```python
from vedo import *

pic = Picture(dataurl + "images/dog.jpg")
dz = 800
x0, x1, y0, y1, _, _ = pic.bounds()
cam = [(x0 + x1) / 2, (y0 + y1) / 2, dz]

lines = Lines(
    [
        [cam, (x0, y0, 0)],
        [cam, (x1, y0, 0)],
        [cam, (x0, y1, 0)],
        [cam, (x1, y1, 0)],
    ],
    c="black",
    lw=2,
)

assem = Assembly([pic, lines, Point(cam)])
assem.orientation([0, -1, 0])

show(assem, axes=1)
```
![Screenshot from 2022-10-21 15-43-05](https://user-images.githubusercontent.com/32848391/197210442-a6625cda-4063-4647-8f0d-0f7c44131823.png)

**Comment by LogWell** [comment]
How to access the four corners of `Picture`, I do not find in `picture.py` and `base.py`?

**Comment by marcomusy** [comment]
You can do it with
`print(assem.unpack(0).bounds()) `

**Comment by LogWell** [comment]
Emm, Bounds and Corner are different if I do some transformations like:
```
pic.origin((1, 2, 2))
pic.orientation((0.2, -0.1, 0.3))
```
so I wonder if there are any ready-made functions that can be used.
![image](https://user-images.githubusercontent.com/34391447/197336344-d47a0eca-2bf1-4608-91e5-9b672356c74e.png)

**Comment by marcomusy** [comment]
You should transform the  `assem` obj not the pic.
I suggest not to use orientation() as it's ignoring `origin()` (bug).
and also there is another small bug about `obj.transform` to being filled for pure rotations...

```python
from vedo import *

settings.use_depth_peeling = True

pic = Picture(dataurl + "images/dog.jpg")
dz = 800
x0, x1, y0, y1, _, _ = pic.bounds()
cam = [(x0 + x1) / 2, (y0 + y1) / 2, dz]

lines = Lines(
    [
        [cam, (x0, y0, 0)],
        [cam, (x1, y0, 0)],
        [cam, (x0, y1, 0)],
        [cam, (x1, y1, 0)],
    ],
    c="black",
    lw=2,
)

corners = Points([(x0, y0), (x1,y0), (x0,y1), (x1,y1)])

assem = Assembly([corners, pic, lines, Point(cam)])
#assem.orientation([1, -1, -2]) # do not use

assem.origin(cam)
assem.rotate_y(90)
assem.rotate_z(-70)
assem.rotate_y(-90)

# T = assem.transform  # not filled (bug), workaround:
T = assem.GetMatrix()

corner_pts = corners.clone().apply_transform(T).points()
print(corner_pts)

show(assem, axes=1)
```

<img width="285" alt="Screenshot 2022-10-22 at 17 12 48" src="https://user-images.githubusercontent.com/32848391/197346855-f6b99d45-e931-4cb7-863b-690163ded7a9.png">

**Comment by LogWell** [comment]
Got it.

**Comment by marcomusy** [comment]
...also it's probably easier if you use `around` to define a pivoting point instead of `origin`:
```python

assem.rotate_y(+90, around=cam)
assem.rotate_z(-90, around=cam)
assem.rotate_y(-90, around=cam)

# instead of:
# assem.origin(cam)
# assem.rotate_y(+90)
# assem.rotate_z(-90)
# assem.rotate_y(-90)
```

to make the cam the pivoting point.
I must see if there is a more intuitive/natural way for the API as these rotations are a bit tricky...

**Comment by LogWell** [comment]
How to handle this boundary when I turn to the back?
![image](https://user-images.githubusercontent.com/34391447/197349842-f5d3e7d7-5ab8-4715-83d5-b3407164aea6.png)

**Comment by marcomusy** [comment]
sorry I don't understand the question.

**Comment by LogWell** [comment]
When I scale this down to around 1, the image plane and the line will penetration:
Note the four corners: 
![image](https://user-images.githubusercontent.com/34391447/197369837-9e0501d9-b1d6-494d-914c-8ca684ec3d0e.png)

```
from vedo import *

settings.use_depth_peeling = True

pic = Picture(dataurl + "images/dog.jpg")
dz = -1000
if True:
    dz = -0.05
    dim = pic.dimensions()
    pic = pic.scale(2 / np.max(dim) * 0.1) 
x0, x1, y0, y1, _, _ = pic.bounds()
cam = [(x0 + x1) / 2, (y0 + y1) / 2, dz]

lines = Lines(
    [
        [cam, (x0, y0, 0)],
        [cam, (x1, y0, 0)],
        [cam, (x0, y1, 0)],
        [cam, (x1, y1, 0)],
    ],
    c="black",
    lw=1.2,
)

assem = Assembly([pic, lines])
assem.origin(cam)
show(assem, axes=0)
```

**Comment by marcomusy** [comment]
I think this is a problem with vtk that has been solved in vtk9.2.2, so I would try:
`pip install vtk -U`

**Comment by LogWell** [comment]
After the upgrade, I still have this problem on my side. But I can use a larger scale to temporarily circumvent this problem.
