### ISSUE TITLE
Get vertices from a ConvexHull

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#880]
Hello!

I'm trying to get the vertices from a ConvexHull made from a set of points. I'm basically doing:

b = vd.ConvexHull(array_of_points)

And i get a ConvexHull object, but when i do b.vertices() i basically get the input points (same as in b.points()).

How can i see the vertices of the bounding box?

**Comment by marcomusy** [comment]
Hi
`vertices()` and `points()` are the same thing.
you may be after `bounds()` which returns the bounding box as 6 nrs `[x0,x1, y0,y1, z0,z1]`.

**Comment by marcomusy** [comment]
the convex hull points are correctly given as `b.points()` which is the same as `b.vertices()`, these are the points of the surrounding surface that "wraps" the original object.

Note that for convex surfaces the convex hull may coincide with the surface itself.

see example:
`examples/advanced/convex_hull.py`

**Comment by ManuGraiph** [comment]
Mmm, then i'm not sure if i'm doing something wrong..

Let's take a simple example.. a 4x4 array of points:

pnts = np.array([[0,0],[0,1],[0,2],[0,3],
                [1,0],[1,1],[1,2],[1,3],
                [2,0],[2,1],[2,2],[2,3],
                [3,0],[3,1],[3,2],[3,3]])

If i get the hull, b = vd.ConvexHull(pnts) it returns the exact same points, while the convex hull is actualy the 4 corners (or the external bordes if it also gets the ones in the mid-arist)

(As a comparison, if i use ConvexHull from scipy, it correctly outputs the corners of the array)

**Comment by marcomusy** [comment]
Thanks for spotting the problem, I just pushed a version with the fix:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

```py
from vedo import *

pnts = np.array([
    [0,0],[0,1],[0,2],[0,3],
    [1,0],[1,1],[1,2],[1,3],
    [2,0],[2,1],[2,2],[2,3],
    [3,0],[3,1],[3,2],[3,3]]
)

b = ConvexHull(pnts) 
print(b.points())
show(Points(pnts), b, axes=8)
```

![Screenshot from 2023-06-12 17-17-39](https://github.com/marcomusy/vedo/assets/32848391/7243b9c1-3e71-4ea0-a451-60b9d6b6bb6f)

Note that you can use `.triangulate()` to fill the outline and make it a mesh.

**Comment by ManuGraiph** [comment]
Thanks a lot Marco!

Btw, vedo is, in my opinion, one of the best python libraries, best contrib. to the scientific community ever!

**Comment by ManuGraiph** [comment]
I'm still not 100% sure that i'm getting the expected behaviour.. now it works, it returns the hull-edge points but:

1. They are not sorted in the "polygon-order"->

array([[1., 0., 0.],
       [2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 3., 0.],
       [1., 3., 0.],
       [2., 3., 0.],
       [3., 0., 0.],
       [3., 1., 0.],
       [3., 2., 0.],
       [3., 3., 0.]], dtype=float32)

2. The hull area that returns is 0.0 (hull.area()). I think this is maybe for the same reason as (1).


Thanks in advance!

**Comment by ManuGraiph** [comment]
Also, i'm not sure if this was intended, but it's also including the collinear points (in this example, the ones in the mid of the arist)

**Comment by marcomusy** [comment]
Yes - I think it's not unintended (a double negation... lol). There is no objectively "correct" behavior as to decide for including or excluding them..

You can only compute areas of triangular meshes (it's a limitation...) but it's easy to fix, you just need to:
```py
area = hull.clone().triangulate().area()
```
returns 9.0

**Comment by ManuGraiph** [comment]
Perfect!

But the sorting order of the points can't be fixed?

**Comment by marcomusy** [comment]
Try:
```py
from vedo import *

pnts = np.array([
    [0,0],[0,1],[0,2],[0,3],
    [1,0],[1,1],[1,2],[1,3],
    [2,0],[2,1],[2,2],[2,3],
    [3,0],[3,1],[3,2],[3,3]]
)

hull = ConvexHull(pnts).join(reset=True).clean()
area = hull.clone().triangulate().area()
vpts = Points(hull.points(), r=8)
labels = vpts.labels2d(scale=2)

show(vpts, labels, hull, f"area={area}", axes=8)
```
![Screenshot from 2023-06-12 19-07-36](https://github.com/marcomusy/vedo/assets/32848391/82d62f20-bfec-468f-b379-8e39a58f5f08)

**Comment by marcomusy** [comment]
This also works:
```py
hull = ConvexHull(pnts).join_segments()[0]
```

**Comment by ManuGraiph** [comment]
`hull = vd.ConvexHull(pnts).join(reset=True).clean()`

Did the trick, thanks!

**Comment by ManuGraiph** [comment]
This is the last question, i swear; it's possible to get the point-ids (position in the original point-array) from the hull obj instead of the points?

For ex.. instead of getting, let's say... [0,0], [1,1] and idk.. [3,3], getting [0,5,12]?

**Comment by marcomusy** [comment]
Feel free to ask anything that is not clear.
You can try the trick of associating data to the points and then interpolate to the closest point (n=1) in the output:

```py
from vedo import *

pnts = np.array([
    [0,0],[0,1],[0,2],[0,3],
    [1,0],[1,1],[1,2],[1,3],
    [2,0],[2,1],[2,2],[2,3],
    [3,0],[3,1],[3,2],[3,3]]
)
pnts = Points(pnts, r=8)
pnts.pointdata["original_id"] = list(range(pnts.npoints))

hull = ConvexHull(pnts).join(reset=True).clean()
# hull = ConvexHull(pnts).join_segments()[0]
hull.interpolate_data_from(pnts, n=1)

area = hull.clone().triangulate().area()
vpts = Points(hull.points(), r=8)
labels = vpts.labels2d(scale=2)

print("original_id", hull.pointdata["original_id"])

show(vpts, labels, hull, f"area={area}", axes=8)
```

outputs:
```
original_id [ 4  8 12 13 14 15 11  7  3  2  1  0]
```

**Comment by ManuGraiph** [comment]
Thanks, i'm gonna try that!
